### PR TITLE
Added gruvbox for intellij idea

### PR DESCRIPTION
**Pull request by kjsebastian**

### CODE REVIEW

**Comment by morhetz** [comment]
Could you provide some description on that PR?
If that's supposed to be updated (as I suppose) intellij idea port should probably be a separate repo that would be linked from [contrib README Ports](https://github.com/morhetz/gruvbox-contrib#ports)

Sorry for late responce

**Comment by kjsebastian** [comment]
Oh oops! I thought this would be a central repo for every editor/ide. I will create a new repo and link in README later.

**Comment by morhetz** [comment]
Thanks!

**Comment by polyzen** [comment]
I don't understand. Isn't the pr just for the colorscheme?

**Comment by morhetz** [comment]
@polyzen not sure if I got you
It was discussed earlier that maintaining and supporting external ports would be easier as separate repos.
@kjsebastian provided gruvbox port for Idea. Since it's pretty complicated and could be updated rather frequently I've requested to provide separate repo for this port.
Originally ports was linked as subrepo but since then it was changed to simple README links as @greduan suggested.

**Comment by polyzen** [comment]
@morhetz, gotcha.

**Pull request closed without merging**
